apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: swiftly
    environment: prod
data:
  AZURE_PROVIDER_ENDPOINT: https://fincog-docai-prod.cognitiveservices.azure.com/
  AZURE_PROVIDER_API_REGION: westus2
  AZURE_PROVIDER_API_VERSION: 2023-10-31-preview
  NATS_URL: nats://nats:4222
  SUPABASE_URL: https://tmjdzzejwjhljivupwhl.supabase.co
