apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-data-pv
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  storageClassName: do-block-storage
  claimRef:
    name: shared-data-pvc
    namespace: prod
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
  volumeName: shared-data-pv
