apiVersion: apps/v1
kind: Deployment
metadata:
  name: case-service
  namespace: prod
  labels:
    environment: prod
    app: swiftly
    service: case-service
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      environment: prod
      app: swiftly
      service: case-service
  template:
    metadata:
      labels:
        environment: prod
        app: swiftly
        service: case-service
    spec:
      containers:
        - name: case-service
          image: singhsays/swiftly-case-service:sha-79e05d7
          volumeMounts:
            - mountPath: /data
              name: shared-data-volume-pv
          env:
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  key: NATS_URL
                  name: app-config
            - name: SUPABASE_DB_URL
              valueFrom:
                secretKeyRef:
                  key: SUPABASE_DB_URL
                  name: app-secrets
            - name: SHARED_DATA_ROOT
              valueFrom:
                configMapKeyRef:
                  key: SHARED_DATA_ROOT
                  name: app-config
      restartPolicy: Always
      volumes:
        - name: shared-data-volume-pv
          persistentVolumeClaim:
            claimName: shared-data-volume-pvc
