apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-classifier
  namespace: prod
  labels:
    environment: prod
    app: swiftly
    service: content-classifier
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      environment: prod
      app: swiftly
      service: content-classifier
  template:
    metadata:
      labels:
        environment: prod
        app: swiftly
        service: content-classifier
    spec:
      containers:
        - name: content-classifier
          image: singhsays/swiftly-content-classifier:sha-2e50d71
          volumeMounts:
            - mountPath: /data
              name: shared-data-volume-pv
          env:
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  key: NATS_URL
                  name: app-config
            - name: SHARED_DATA_ROOT
              valueFrom:
                configMapKeyRef:
                  key: SHARED_DATA_ROOT
                  name: app-config
      restartPolicy: Always
      volumes:
        - name: shared-data-volume-pv
          persistentVolumeClaim:
            claimName: shared-data-volume-pvc
