apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-classifier
  namespace: prod
  labels:
    environment: prod
    app: swiftly
    service: content-classifier
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      environment: prod
      app: swiftly
      service: content-classifier
  template:
    metadata:
      labels:
        environment: prod
        app: swiftly
        service: content-classifier
    spec:
      containers:
        - name: content-classifier
          image: singhsays/swiftly-content-classifier:sha-541e4b7
          env:
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  key: NATS_URL
                  name: app-config
      restartPolicy: Always
