apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
spec:
  destination:
    namespace: swiftly-prod
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://nats-io.github.io/k8s/helm/charts/"
    targetRevision: 1.1.9
    chart: nats
    helm:
      parameters:
        - name: config.jetstream.enabled
          value: "true"
        - name: config.jetstream.fileStore.dir
          value: "/data/nats"
        - name: config.jetstream.fileStore.pvc.name
          value: "shared-data-pvc"
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
