apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swiftly-api-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/fincognition/fincog-gitops.git
    targetRevision: HEAD
    path: environments/dev/api-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: swiftly-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - PrunePropagationPolicy=Foreground
      - PruneLast=true
