apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-stack-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/fincognition/fincog-gitops.git
    targetRevision: HEAD
    path: stacks/prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - PrunePropagationPolicy=Foreground
      - PruneLast=true
